name: build-wasm
on: workflow_dispatch
jobs:

  build-wasm:
    runs-on: ubuntu-22.04
    steps:    
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: 3.1.43

      - name: Install Prerequisites
        run:  sudo apt-get install -y wget git

      - name: Download source
        run: |
          wget https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.17.tar.gz
          mkdir libiconv && tar -xf libiconv-1.17.tar.gz -C libiconv --strip-components=1
        
      - name: Build
        run: |
          mkdir -p build
          cd libiconv
          emconfigure ./configure --prefix="$PWD/../build" --enable-static --disable-shared
          emmake make install
          # ./src/iconv
          rm ../build/bin/iconv && emcc -Oz -o ../build/bin/iconv.wasm   ./lib/iconv.o  ./srclib/libicrt.a ../build/lib/libiconv.a
        
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
#      - name: Create Release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: chown $(whoami) -R . && gh --version && gh release create build_wasm_${{github.sha}}_${{ github.run_id }}_${{ github.run_attempt }} -t "Wasm assets" busytex_pipeline.js busytex_worker.js build/versions.txt build/wasm/busytex.js build/wasm/busytex.wasm  source/texmfrepo.txt build/texlive-basic/texmf-dist/dvipdfmx/dvipdfmx.cfg build/texlive-basic/texmf-dist/web2c/texmf.cnf build/texlive-basic/texmf-dist/web2c/updmap.cfg build/texlive-basic.profile build/texlive-basic.tar.gz build/texlive-basic.txt  build/wasm/texlive-basic.js build/wasm/texlive-basic.data build/wasm/texlive-basic.js.providespackage.txt build/texlive-full.txt build/texlive-full.profile $(printf "build/wasm/ubuntu-%s.js " $UBUNTUPACKAGES) $(printf "build/wasm/ubuntu-%s.data " $UBUNTUPACKAGES) $(printf "build/wasm/ubuntu-%s.js.skip.txt " $UBUNTUPACKAGES) $(printf "build/wasm/ubuntu-%s.js.good.txt " $UBUNTUPACKAGES) $(printf "build/wasm/ubuntu-%s.js.providespackage.txt " $UBUNTUPACKAGES) $(printf "build/wasm/ubuntu-%s.js.ubuntu.txt " $UBUNTUPACKAGES)
