name: build-wasm
on: workflow_dispatch
jobs:

  build-wasm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v13
        with:
          version: 3.1.43

      - name: Download source
        run: make libiconv
        
      - name: Build
        run: make iconv.html -j2
        
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: iconv.html
